on:
  workflow_call:
        inputs:
          name:
          required: true
          type: string
          
jobs:
  reusable_workflow_job:
    runs-on: ubuntu-latest
    environment: production
    steps:
      name: printing name and exec from re-usable workflow
      run: echo the name is ${{ inputs.name }}
